07 vote on review
StaceyCP/NC-Games pull request #4
Opened 2023-02-07 16:23 UTC by StaceyCP

Voting on a review is complete with error handling 👍

2023-02-07 16:53 UTC, NRMSMITH reviewed
can you rethink your voting system - love/Like/dislike is very arbitrary and not intuitive for the user. Buttons that read the amount of votes being given might be more intuitive for a screen reader or someone who is ESL. 

Also check comment about optimistic rendering - we should be able to see the vote increase before the error notice(which you might want to make a simple sentence on the page rather than changing the entire page).

2023-02-07 16:53 UTC, NRMSMITH commented on src/components/ReviewPage.jsx
> +        vote.inc_votes = num
Ideally, you should change the state before the api call, as that way you are optimistically rendering the desired result. The catch block below is great too.

2023-02-08 09:47 UTC, MKD01 requested changes
Great work over all but please do make those changes first

2023-02-08 09:47 UTC, MKD01 commented on src/components/ReviewPage.jsx
>                      <hr></hr>
I really like the idea behind this, but it doesnt seem to work the way you may think.

Clicking the like or dislike buttons the first time shows an error modal pop up, which i dont think should be the case.

After clicking the like or dislike the opposite can be clicked but does not change the vote amount.

If you click one of the buttons and then click else where on the page the button that was selected is no longer obvious, but that is just something to consider at this point.

2023-02-08 10:44 UTC, MKD01 approved these changes
Great work so far, but once a user has voted they cannot remove their vote or vote the opposite way.

2023-02-08 11:07 UTC, merged